# Author: Danny van Dijk | Flutgets.com
# Copyright FlutGets (https://flutgets.com/)
# Created: 05 2023
name: flutgetheme
description: A Flutter project from FlutGets.com
homepage: https://flutgets.com
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Needed to make the Theme Manager work
  provider: ^6.0.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700